version: '3.4'

services:
  confluence:
    image: haxqer/confluence:9.2.1
    container_name: confluence-srv
    environment:
      - TZ=America/Denver
      # Uncomment and adjust JVM options as needed
      # - JVM_MINIMUM_MEMORY=1g
      # - JVM_MAXIMUM_MEMORY=12g
      # - JVM_CODE_CACHE_ARGS='-XX:InitialCodeCacheSize=1g -XX:ReservedCodeCacheSize=8g'
    depends_on:
      - mysql
    volumes:
      - home_data:/var/confluence
    restart: always
    networks:
      - network-bridge
    labels:
      - traefik.enable=true
      - traefik.http.routers.confluence.entryPoints=web
      - traefik.http.middlewares.confluence-headers.headers.customrequestheaders.X-Forwarded-Proto=https
      - traefik.http.routers.confluence.middlewares=confluence-headers
      - traefik.http.services.confluence.loadbalancer.server.port=8090
  mysql:
    image: mysql:8.0
    container_name: mysql-confluence
    environment:
      - TZ=UTC
      - MYSQL_DATABASE=confluence
      - MYSQL_ROOT_PASSWORD=123456
      - MYSQL_USER=confluence
      - MYSQL_PASSWORD=123123
    command: [
      'mysqld',
      '--character-set-server=utf8mb4',
      '--collation-server=utf8mb4_bin',
      '--transaction-isolation=READ-COMMITTED',
      '--innodb_log_file_size=256M',
      '--max_allowed_packet=256M',
      '--log_bin_trust_function_creators=1'
    ]
    volumes:
      - mysql_data:/var/lib/mysql
    restart: always
    networks:
      - network-bridge

networks:
  network-bridge:
    driver: bridge

volumes:
  home_data:
    external: false
  mysql_data:
    external: false
